# Generated by Django 4.1.7 on 2023-03-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_price',
            field=models.CharField(max_length=20),
        ),
    ]
